### ISSUE TITLE
operating-system-logos + shields.io

### ISSUE THREAD

**Issue by codehangen** [EgoistDeveloper/operating-system-logos#3]
Hi everyone.

Please, see this [shields.io + operating-system-logos](https://github.com/badges/shields/discussions/8709) - *What do you all think of the idea of adding operating-system-logos to shields.io?*

**Comment by EgoistDeveloper** [comment]
Hi, I like the concept but I collected these icons from the web and there is no SVG version. I think some logos are outdated. If you want to use only the PNG version it's OK. We can use them for shields.io

**Comment by EgoistDeveloper** [comment]
> thank you for feedback. But... please, could you help me? Could you comment on the link I sent what do you think of the idea?

Done.

> I would like to make this dream possible. _So... I believe the PNG version is good to put on shields._

Yes, I thought to create SVG versions but I do have not enough time (and I am not a designer). Maybe someone can help us.
