### ISSUE TITLE
NixOS in operating-system-logos

### ISSUE THREAD

**Issue by ghost** [EgoistDeveloper/operating-system-logos#4]
Hi EgoistDeveloper.

*How can I add NixOS logo here?*
<img src="https://user-images.githubusercontent.com/111701513/213327216-d51f29db-819e-4a82-9fe9-cd09282b024e.png" width="250px">

*questions*
1. How can I add more logos to this repository?
2. How can I contribute to this repository?

**Comment by EgoistDeveloper** [comment]
Hi @codehangen, you can follow [contribution](https://github.com/EgoistDeveloper/operating-system-logos#contribution) notes. And don't forget I'm only accepting 4:4 logos. Your example is too wide, you should consider using only icons or you can manipulate them.

Also, you can find NixOS artwork assets [here](https://github.com/NixOS/nixos-artwork).
